# Shallow Neural Network in Keras

#### Build a shallow neural network to classify MNIST digits

In [1]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


#### Load data

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
y_train.shape

(60000,)

In [5]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0, 9,
       1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9, 3, 9,
       8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5, 6, 1, 0,
       0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9, 0, 4, 6, 7,
       4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [6]:
X_test.shape

(10000, 28, 28)

In [7]:
X_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [8]:
y_test.shape

(10000,)

In [9]:
y_test[0]

7

#### Preprocess data

In [10]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [11]:
X_train /= 255
X_test /= 255

In [12]:
X_test[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [13]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [14]:
y_test[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.])

#### Build neural network layers

In [15]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))

In [16]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [17]:
(64*784)

50176

In [18]:
(64*784)+64

50240

In [19]:
(10*64)+10

650

In [20]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

In [21]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 1s - loss: 0.0919 - acc: 0.1026 - val_loss: 0.0913 - val_acc: 0.1054
Epoch 2/200
60000/60000 [==============================] - 1s - loss: 0.0909 - acc: 0.1053 - val_loss: 0.0906 - val_acc: 0.1135
Epoch 3/200
60000/60000 [==============================] - 1s - loss: 0.0904 - acc: 0.1218 - val_loss: 0.0901 - val_acc: 0.1407
Epoch 4/200
60000/60000 [==============================] - 1s - loss: 0.0899 - acc: 0.1507 - val_loss: 0.0897 - val_acc: 0.1680
Epoch 5/200
60000/60000 [==============================] - 1s - loss: 0.0896 - acc: 0.1742 - val_loss: 0.0894 - val_acc: 0.1877
Epoch 6/200
60000/60000 [==============================] - 1s - loss: 0.0892 - acc: 0.1937 - val_loss: 0.0891 - val_acc: 0.2071
Epoch 7/200
60000/60000 [==============================] - 1s - loss: 0.0889 - acc: 0.2115 - val_loss: 0.0887 - val_acc: 0.2297
Epoch 8/200
60000/60000 [=============================

60000/60000 [==============================] - 1s - loss: 0.0650 - acc: 0.5402 - val_loss: 0.0643 - val_acc: 0.5452
Epoch 65/200
60000/60000 [==============================] - 1s - loss: 0.0646 - acc: 0.5437 - val_loss: 0.0638 - val_acc: 0.5491
Epoch 66/200
60000/60000 [==============================] - 1s - loss: 0.0641 - acc: 0.5476 - val_loss: 0.0634 - val_acc: 0.5527
Epoch 67/200
60000/60000 [==============================] - 1s - loss: 0.0636 - acc: 0.5519 - val_loss: 0.0629 - val_acc: 0.5571
Epoch 68/200
60000/60000 [==============================] - 1s - loss: 0.0632 - acc: 0.5551 - val_loss: 0.0624 - val_acc: 0.5614
Epoch 69/200
60000/60000 [==============================] - 1s - loss: 0.0627 - acc: 0.5599 - val_loss: 0.0620 - val_acc: 0.5671
Epoch 70/200
60000/60000 [==============================] - 1s - loss: 0.0623 - acc: 0.5637 - val_loss: 0.0615 - val_acc: 0.5711
Epoch 71/200
60000/60000 [==============================] - 1s - loss: 0.0618 - acc: 0.5687 - val_loss: 0.0611

60000/60000 [==============================] - 1s - loss: 0.0421 - acc: 0.7929 - val_loss: 0.0412 - val_acc: 0.8074
Epoch 128/200
60000/60000 [==============================] - 1s - loss: 0.0419 - acc: 0.7947 - val_loss: 0.0409 - val_acc: 0.8089
Epoch 129/200
60000/60000 [==============================] - 1s - loss: 0.0416 - acc: 0.7965 - val_loss: 0.0406 - val_acc: 0.8101
Epoch 130/200
60000/60000 [==============================] - 1s - loss: 0.0413 - acc: 0.7984 - val_loss: 0.0403 - val_acc: 0.8114
Epoch 131/200
60000/60000 [==============================] - 1s - loss: 0.0411 - acc: 0.8001 - val_loss: 0.0401 - val_acc: 0.8123
Epoch 132/200
60000/60000 [==============================] - 1s - loss: 0.0408 - acc: 0.8020 - val_loss: 0.0398 - val_acc: 0.8139
Epoch 133/200
60000/60000 [==============================] - 1s - loss: 0.0406 - acc: 0.8039 - val_loss: 0.0396 - val_acc: 0.8154
Epoch 134/200
60000/60000 [==============================] - 1s - loss: 0.0403 - acc: 0.8055 - val_loss:

60000/60000 [==============================] - 1s - loss: 0.0301 - acc: 0.8525 - val_loss: 0.0290 - val_acc: 0.8614
Epoch 190/200
60000/60000 [==============================] - 1s - loss: 0.0299 - acc: 0.8531 - val_loss: 0.0289 - val_acc: 0.8616
Epoch 191/200
60000/60000 [==============================] - 1s - loss: 0.0298 - acc: 0.8536 - val_loss: 0.0288 - val_acc: 0.8618
Epoch 192/200
60000/60000 [==============================] - 1s - loss: 0.0297 - acc: 0.8540 - val_loss: 0.0286 - val_acc: 0.8622
Epoch 193/200
60000/60000 [==============================] - 1s - loss: 0.0296 - acc: 0.8544 - val_loss: 0.0285 - val_acc: 0.8626
Epoch 194/200
60000/60000 [==============================] - 1s - loss: 0.0294 - acc: 0.8547 - val_loss: 0.0284 - val_acc: 0.8631
Epoch 195/200
60000/60000 [==============================] - 1s - loss: 0.0293 - acc: 0.8550 - val_loss: 0.0283 - val_acc: 0.8636
Epoch 196/200
60000/60000 [==============================] - 1s - loss: 0.0292 - acc: 0.8555 - val_loss:

In [23]:
model.evaluate(X_test, y_test)

 8736/10000 [=========================>....] - ETA: 0s

[0.027673055118322371, 0.8659]