# Shallow Neural Network in Keras

Build a shallow neural network to classify MNIST digits

#### Set seed for reproducibility

In [1]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [3]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

#### Load data

In [4]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 2s 0us/step


In [5]:
X_train.shape

(60000, 28, 28)

In [6]:
y_train.shape

(60000,)

In [7]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [8]:
X_test.shape

(10000, 28, 28)

In [9]:
X_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [10]:
y_test.shape

(10000,)

In [11]:
y_test[0]

7

#### Preprocess data

In [12]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [13]:
X_train /= 255
X_test /= 255

In [14]:
X_test[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [15]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [16]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

#### Design neural network architecture

In [17]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))

In [18]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [19]:
(64*784)

50176

In [20]:
(64*784)+64

50240

In [21]:
(10*64)+10

650

#### Configure model

In [22]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train!

In [23]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 3s 43us/step - loss: 0.0915 - acc: 0.0895 - val_loss: 0.0911 - val_acc: 0.0955
Epoch 2/200
60000/60000 [==============================] - 3s 43us/step - loss: 0.0908 - acc: 0.1058 - val_loss: 0.0905 - val_acc: 0.1162
Epoch 3/200
60000/60000 [==============================] - 2s 32us/step - loss: 0.0903 - acc: 0.1406 - val_loss: 0.0901 - val_acc: 0.1513
Epoch 4/200
60000/60000 [==============================] - 2s 39us/step - loss: 0.0899 - acc: 0.1925 - val_loss: 0.0897 - val_acc: 0.2058
Epoch 5/200
60000/60000 [==============================] - 3s 44us/step - loss: 0.0895 - acc: 0.2401 - val_loss: 0.0893 - val_acc: 0.2424
Epoch 6/200
60000/60000 [==============================] - 2s 33us/step - loss: 0.0891 - acc: 0.2706 - val_loss: 0.0889 - val_acc: 0.2715
Epoch 7/200
60000/60000 [==============================] - 2s 32us/step - loss: 0.0888 - acc: 0.2905 - val_loss: 0.0886 - 

60000/60000 [==============================] - 2s 27us/step - loss: 0.0666 - acc: 0.5921 - val_loss: 0.0660 - val_acc: 0.5985
Epoch 60/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0661 - acc: 0.5962 - val_loss: 0.0655 - val_acc: 0.6028
Epoch 61/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0656 - acc: 0.6003 - val_loss: 0.0651 - val_acc: 0.6068
Epoch 62/200
60000/60000 [==============================] - 2s 38us/step - loss: 0.0652 - acc: 0.6041 - val_loss: 0.0646 - val_acc: 0.6102
Epoch 63/200
60000/60000 [==============================] - 2s 33us/step - loss: 0.0647 - acc: 0.6080 - val_loss: 0.0641 - val_acc: 0.6136
Epoch 64/200
60000/60000 [==============================] - 2s 25us/step - loss: 0.0642 - acc: 0.6117 - val_loss: 0.0636 - val_acc: 0.6163
Epoch 65/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0638 - acc: 0.6152 - val_loss: 0.0632 - val_acc: 0.6189
Epoch 66/200
60000/60000 [==============

60000/60000 [==============================] - 1s 24us/step - loss: 0.0438 - acc: 0.7647 - val_loss: 0.0429 - val_acc: 0.7728
Epoch 118/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0435 - acc: 0.7665 - val_loss: 0.0426 - val_acc: 0.7756
Epoch 119/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0432 - acc: 0.7683 - val_loss: 0.0423 - val_acc: 0.7779
Epoch 120/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0429 - acc: 0.7700 - val_loss: 0.0420 - val_acc: 0.7790
Epoch 121/200
60000/60000 [==============================] - 2s 33us/step - loss: 0.0426 - acc: 0.7712 - val_loss: 0.0417 - val_acc: 0.7806
Epoch 122/200
60000/60000 [==============================] - 2s 34us/step - loss: 0.0423 - acc: 0.7727 - val_loss: 0.0414 - val_acc: 0.7822
Epoch 123/200
60000/60000 [==============================] - 2s 25us/step - loss: 0.0421 - acc: 0.7746 - val_loss: 0.0411 - val_acc: 0.7849
Epoch 124/200
60000/60000 [=======

60000/60000 [==============================] - 2s 32us/step - loss: 0.0314 - acc: 0.8452 - val_loss: 0.0304 - val_acc: 0.8549
Epoch 176/200
60000/60000 [==============================] - 2s 31us/step - loss: 0.0312 - acc: 0.8460 - val_loss: 0.0302 - val_acc: 0.8550
Epoch 177/200
60000/60000 [==============================] - 2s 32us/step - loss: 0.0311 - acc: 0.8467 - val_loss: 0.0301 - val_acc: 0.8558
Epoch 178/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0309 - acc: 0.8475 - val_loss: 0.0299 - val_acc: 0.8561
Epoch 179/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0308 - acc: 0.8483 - val_loss: 0.0298 - val_acc: 0.8567
Epoch 180/200
60000/60000 [==============================] - 1s 25us/step - loss: 0.0307 - acc: 0.8489 - val_loss: 0.0297 - val_acc: 0.8571
Epoch 181/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0305 - acc: 0.8496 - val_loss: 0.0295 - val_acc: 0.8578
Epoch 182/200
60000/60000 [=======

In [24]:
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 1s 73us/step


[0.02717626480460167, 0.8658]